travis:
  secure:
    BINSTAR_TOKEN: dYPuuwYdo5h4euoxfp4TDxmwNC2jrTwOVXV+npSMOJWIArFhFn4TrHSdrdu7wPUhFKwDDbrrUFw0WHk/aEaEkLPj0dxrgxiymLE8dI+Aun4EbEjYc/aJPriJB5skPt+FYffH2TO2BFZ1VEQjcc9rz8lsPzeiiMxP9bDgU7i54gD1FLTUe+bhzTGR88lV9WEIoA7mU7olvDxjyrT0emj9A0EKXWurn2HpofS2QRhM9XbvO+gmY+IcXzM3iNQZkRG1+TH8UCif2/9GK3VP5GkDwYqUtYn9VLXLdLNyfyU9DNeeu1gbvCrHE4BYWs/eaGGpfKjm2A+W8G/1sccnKTsP9Vfs8RzcT+dXgLV32bhxhaTh0DNCTsaaQo05nDXiKlID41ItpQHr20htmule/rd55T5iVta5v7PzDe9EhkIFXIoskX1ltB9P+kpb8OotYzXtsWQ2B5cw0YMPXRa2l1nMKkel0/8a1kzpc1VnZcN8jnYudmp0tleCDSxj9D03+MdONAWvgvCYdx7iqEA3mdpYepgXnLLKuoFSwXEz5xAzc9CPM9SrHJjWd9AZLKenP8hu4kAkP34laJvQzZYIC/K7m51zPfyy0yHu5vjp+osvjMWgliW8QJcJSr9/VOesCj+9Nkhe6kq7n4HALCVV/XArsxrzfobEtuXvGDBbZvbWa+Y=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
